#!/bin/bash

# License: GNU General Public License v2
# See the COPYING file for details

gen_html () {
    LDVIDEOWIDTH=800
    LDVIDEOHEIGHT=450
    VIDEOFILE=$PREFIX-$FILENAME.webm
    LDVIDEOFILE=$PREFIX-$FILENAME-${LDVIDEOHEIGHT}p.webm
    VIDEOCAP=$CAPS/$PREFIX-$FILENAME.jpg
    VIDEOCAPTHUMB=$CAPS/$PREFIX-$FILENAME-thumb.jpg
    VIDEO=$VIDEOPATH/$VIDEOFILE
    LDVIDEO=$VIDEOPATH/$LDVIDEOFILE

    echo -n "<b>$SPEAKER</b>"

    if [ "$FILENAME" != "" ]
    then
	DURATION=`LANG=C mkvinfo $VIDEO | grep Duration | cut -f4 -d' ' | cut -f1 -ds`
	MINUTES=`echo $DURATION/60 | bc`
	SIZE=`ls -lh $VIDEO | awk '{ print $5 }'`
	LDSIZE=`ls -lh $LDVIDEO | awk '{ print $5 }'`

       # Capturing a frame at instant 300 (5 minutes)
       # Usually, the speaker is ready and still talking

       avconv -ss 300 -i $VIDEO -vframes 1 output%d.jpg
       if ! -f output1.jpg ; then
           avconv -ss 100 -i $VIDEO -vframes 1 output%d.jpg ;
       fi
       mv output1.jpg $VIDEOCAP
       convert $VIDEOCAP -resize 200 $VIDEOCAPTHUMB

       echo -n "<a href=\"$WWWDIR/$VIDEOCAP\"><img class=\"alignright\" src=\"$WWWDIR/$VIDEOCAPTHUMB\" alt=\"Video capture\"/></a>"
    fi
    echo -n "<br/>"

    # Generating html

    if [ "$COMPANY" != "" ]
    then
        echo -n "$COMPANY<br/>"
    fi

    if [ "$LINK" != "" ]
    then
        echo -n "<a href=\"$LINK\">$TITLE</a><br/>"
    else
        echo -n "$TITLE<br/>"
    fi

    if [ "$SLIDES" != "" ]
    then
        echo -n "<a href=\"$SLIDES\">Slides</a><br/>"
    fi

    if [ "$AUDIO" != "" ]
    then
        echo -n "<a href=\"$AUDIO\">Audio Recording</a><br/>"
    fi

    if [ -f "$VIDEO" ]
    then
        echo -n "Video ($MINUTES minutes):<br/>"
        echo -n "<a href=\"$WWWDIR/$VIDEOFILE\">full HD</a> ($SIZE), "
        echo -n "<a href=\"$WWWDIR/$LDVIDEOFILE\">${LDVIDEOWIDTH}x${LDVIDEOHEIGHT}</a> ($LDSIZE)<br/>"
    fi

    echo "<br/>"
}

CAPS=vidcaps
VIDEOPATH=$1
mkdir -p $CAPS

cat conf-list.txt | grep -v "^#" | while read talk ; do
    EVENT_YEAR=$(echo $talk | cut -f1 -d'|')
    EVENT=$(echo $EVENT_YEAR | cut -f1 -d'-')
    YEAR=$(echo $EVENT_YEAR | cut -f2 -d'-')
    SPEAKER=$(echo $talk | cut -f2 -d'|')
    COMPANY=$(echo $talk | cut -f3 -d'|')
    TITLE=$(echo $talk | cut -f4 -d'|')
    FILENAME=$(echo $talk | cut -f5 -d'|')
    LINK=$(echo $talk | cut -f6 -d'|')
    SLIDES=$(echo $talk | cut -f7 -d'|')
    AUDIO=$(echo $talk | cut -f8 -d'|')

    PREFIX=$EVENT_YEAR
    WWWDIR=/pub/video/$YEAR/$EVENT

    gen_html < /dev/null
done
