#!/bin/sh
#
# Script to encode multiple AVCHD videos to VP8/Vorbis in a WebM container
#
# Required Ubuntu packages:
# libav-tools inkscape mkvtoolnix
#
# The tested libav version is Git version
# 1f4ea4e068f1131bff6c246308f52acbf1347cc2.
#
# License: GNU General Public License v2
# See the COPYING file for details

encode_vp8 () {

    echo "Processing $FILENAME..."

    OUTPUT=$OUTDIR/${PREFIX}-${FILENAME}-${HEIGHT}p.webm
    OUTPUT_HD=$OUTDIR/${PREFIX}-${FILENAME}.webm

    if [ -f "$OUTPUT" ]
    then
	echo "Skipping $OUTPUT... already generated"
	continue
    fi

    dir=tmp-${FILENAME}
    mkdir -p $dir

    # Encode video

    VIDEO_HD=$dir/video-hd.webm
    VIDEO=$dir/video.webm
    AVCONV_VIDEO_OPTS="-threads $CPUS -y -i - -f webm -vcodec libvpx -vf yadif -r 25 -strict experimental"

    echo "Encode high-res video"
    cat ${FILENAME}*.mts | avconv ${AVCONV_VIDEO_OPTS} -s ${WIDTH_HD}x${HEIGHT_HD} -acodec vorbis -b 800k $VIDEO_HD
    if [ $? -ne 0 ] ; then exit 1 ; fi

    echo "Encode low-res video"
    cat ${FILENAME}*.mts | avconv ${AVCONV_VIDEO_OPTS} -s ${WIDTH}x${HEIGHT} -acodec vorbis -b 400k $VIDEO
    if [ $? -ne 0 ] ; then exit 1 ; fi

    # Generate intro picture

    echo "Generate introduction picture"

    COVER_SVG=$dir/cover.svg
    COVER_HD=$dir/cover-hd.png
    COVER=$dir/cover.png

    cat $COVER_TEMPLATE | sed "s|TITLE|$TITLE|" | sed "s|SPEAKER|$SPEAKER|" | sed "s|COMPANY|$COMPANY|" > $COVER_SVG
    if [ $? -ne 0 ]
    then
    	exit 1
    fi

    TITLE_LENGTH=$(echo $TITLE | wc -c)
    if [ $TITLE_LENGTH -gt 100 ] ; then
       sed -i "s/font-size:36px/font-size:28px/" $COVER_SVG
    elif [ $TITLE_LENGTH -gt 80 ] ; then
       sed -i "s/font-size:36px/font-size:32px/" $COVER_SVG
    fi

    inkscape -h $HEIGHT_HD -w $WIDTH_HD -e $COVER_HD $COVER_SVG 2> /dev/null
    if [ $? -ne 0 ] ; then exit 1 ; fi

    inkscape -h $HEIGHT -w $WIDTH -e $COVER $COVER_SVG 2> /dev/null
    if [ $? -ne 0 ] ; then exit 1 ; fi

    # Generate intro video
    echo "Generate intro video"

    INTRO_HD=$dir/intro-hd.webm
    INTRO=$dir/intro.webm
    avconv -y \
	-f image2 -loop 1 -i $COVER_HD -r 25 -f webm -vcodec libvpx -t $INTRO_DURATION \
	-ar 48000 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -strict experimental -acodec vorbis -t $INTRO_DURATION \
	-map 0:0 -map 1:0 $INTRO_HD
    if [ $? -ne 0 ] ; then exit 1 ; fi

    avconv -y \
	-f image2 -loop 1 -i $COVER -r 25 -f webm -vcodec libvpx -t $INTRO_DURATION \
	-ar 48000 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -strict experimental -acodec vorbis -t $INTRO_DURATION \
	-map 0:0 -map 1:0 $INTRO
    if [ $? -ne 0 ] ; then exit 1 ; fi

    # Merge all the components (no reencoding needed)

    echo "Merge high-res video"
    TMP=$dir/output.webm
    LANG=C mkvmerge --title "$SPEAKER - $TITLE" -o $TMP $INTRO_HD +${VIDEO_HD}
    if [ $? -ne 0 ] ; then exit 1 ; fi
    mv -f $TMP $OUTPUT_HD

    echo "Merge low-res video"
    LANG=C mkvmerge --title "$SPEAKER - $TITLE" -o $TMP $INTRO +${VIDEO}
    if [ $? -ne 0 ] ; then exit 1 ; fi
    mv -f $TMP $OUTPUT

    # Clean
    rm -rf $dir
}

gen_cover () {
    # Generate intro picture

    COVER_SVG=$OUTDIR/cover.svg
    COVER_HD=$OUTDIR/cover-hd-$FILENAME.png
    COVER=$OUTDIR/cover-$FILENAME.png

    cat $COVER_TEMPLATE | sed "s|TITLE|$TITLE|" | sed "s|SPEAKER|$SPEAKER|" | sed "s|COMPANY|$COMPANY|" > $COVER_SVG
    if [ $? -ne 0 ]
    then
    	exit 1
    fi

    TITLE_LENGTH=$(echo $TITLE | wc -c)
    if [ $TITLE_LENGTH -gt 100 ] ; then
       sed -i "s/font-size:36px/font-size:28px/" $COVER_SVG
    elif [ $TITLE_LENGTH -gt 80 ] ; then
       sed -i "s/font-size:36px/font-size:32px/" $COVER_SVG
    fi

    inkscape -h $HEIGHT_HD -w $WIDTH_HD -e $COVER_HD $COVER_SVG 2> /dev/null
    if [ $? -ne 0 ]
    then
    	exit 1
    fi

#    inkscape -h $HEIGHT -w $WIDTH -e $COVER $COVER_SVG 2> /dev/null
#    if [ $? -ne 0 ]
#    then
#    	exit 1
#    fi
}

# Inits

WIDTH=800
HEIGHT=450
WIDTH_HD=1920
HEIGHT_HD=1080
CPUS=2
INTRO_DURATION=5
AUDIO_RATE=48000
OUTDIR=webm

mkdir -p $OUTDIR

cat conf-list.txt | grep -v "^#" | while read talk ; do
    EVENT=$(echo $talk | cut -f1 -d'|')
    SPEAKER=$(echo $talk | cut -f2 -d'|')
    COMPANY=$(echo $talk | cut -f3 -d'|')
    TITLE=$(echo $talk | cut -f4 -d'|')
    FILENAME=$(echo $talk | cut -f5 -d'|')

    if [ "$EVENT" = "elce-2012" ] ; then
	COVER_TEMPLATE=video-cover-elce.svg
	PREFIX=elce-2012
    else
        echo "Unknown event $EVENT, abording"
	exit 1
    fi

#    gen_cover < /dev/null
    encode_vp8 < /dev/null
done
